# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-21 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likesbooks', '0003_auto_20181020_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likesbooks.User'),
        ),
    ]
