# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksauthors', '0004_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(),
        ),
    ]
