# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksauthors', '0009_auto_20181020_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
