# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksauthors', '0010_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='booksauthors.Author'),
        ),
    ]
