# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181022_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
